In [9]:
# test_preprocess.ipynb

import pandas as pd
import sys
import os

# Add src folder to path
sys.path.append("H:\\MLOps\\CustomerChurn-ML\\src\\data")

In [10]:
from preprocess import preprocess_data

In [13]:
from pathlib import Path
path = Path(r'H:\MLOps\CustomerChurn-ML\data\raw\data.csv')
df = pd.read_csv(path)
df.head()

,AccountAge,MonthlyCharges,TotalCharges,SubscriptionType,PaymentMethod,PaperlessBilling,ContentType,MultiDeviceAccess,DeviceRegistered,ViewingHoursPerWeek,...,ContentDownloadsPerMonth,GenrePreference,UserRating,SupportTicketsPerMonth,Gender,WatchlistSize,ParentalControl,SubtitlesEnabled,CustomerID,Churn
0,20,11.055215,221.104302,Premium,Mailed check,No,Both,No,Mobile,36.758104,...,10,Sci-Fi,2.176498,4,Male,3,No,No,CB6SXPNVZA,0
1,57,5.175208,294.986882,Basic,Credit card,Yes,Movies,No,Tablet,32.450568,...,18,Action,3.478632,8,Male,23,No,Yes,S7R2G87O09,0
2,73,12.106657,883.785952,Basic,Mailed check,Yes,Movies,No,Computer,7.395160,...,23,Fantasy,4.238824,6,Male,1,Yes,Yes,EASDC20BDT,0
3,32,7.263743,232.439774,Basic,Electronic check,No,TV Shows,No,Tablet,27.960389,...,30,Drama,4.276013,2,Male,24,Yes,Yes,NPF69NT69N,0
4,57,16.953078,966.325422,Premium,Electronic check,Yes,TV Shows,No,TV,20.083397,...,20,Comedy,3.616170,4,Female,0,No,No,4LGYPK7VOL,0

In [14]:
preprocessed_df = preprocess_data(df)
preprocessed_df.head()

H:\MLOps\CustomerChurn-ML\src\data\preprocess.py:17: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[binary_col] = df[binary_col].replace(

,AccountAge,MonthlyCharges,TotalCharges,PaperlessBilling,MultiDeviceAccess,ViewingHoursPerWeek,AverageViewingDuration,ContentDownloadsPerMonth,UserRating,SupportTicketsPerMonth,...,PaymentMethod_Mailed check,ContentType_Movies,ContentType_TV Shows,DeviceRegistered_Mobile,DeviceRegistered_TV,DeviceRegistered_Tablet,GenrePreference_Comedy,GenrePreference_Drama,GenrePreference_Fantasy,GenrePreference_Sci-Fi
0,20,11.055215,221.104302,0,0,36.758104,63.531377,10,2.176498,4,...,1,0,0,1,0,0,0,0,0,1
1,57,5.175208,294.986882,1,0,32.450568,25.725595,18,3.478632,8,...,0,1,0,0,0,1,0,0,0,0
2,73,12.106657,883.785952,1,0,7.395160,57.364061,23,4.238824,6,...,1,1,0,0,0,0,0,0,1,0
3,32,7.263743,232.439774,0,0,27.960389,131.537507,30,4.276013,2,...,0,0,1,0,0,1,0,1,0,0
4,57,16.953078,966.325422,1,0,20.083397,45.356653,20,3.616170,4,...,0,0,1,0,1,0,1,0,0,0